# color theme
[general]
# import = ["./themes/gruvbox-material.toml"]
import = ["./themes/kanagawa-dragon.toml"]
# import = ["./themes/tokyo-night-enhanced.toml"]

[cursor.style]
shape = "Block"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 10
y = 10

