[colors.primary]
background = '#1F1F1F'
foreground = '#D4D4D4'

[colors.cursor]
text = "#1F1F1F"
cursor = "#D4D4D4"

[colors.normal]
black = "#1F1F1F"
red = "#F44747"
green = "#6A9955"
yellow = "#795E26"
blue = "#007ACC"
magenta = "#C586C0"
cyan = "#4FC1FF"
white = "#D4D4D4"

[colors.bright]
black = "#808080"
[cursor]
style = { shape = "Block", blinking = "On" }

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 10
y = 10
