[colors]
indexed_colors = [
    { index = 16, color = "#B6927B" },
    { index = 17, color = "#B6927B" },
]

[colors.primary]
background = "#282828"
foreground = "#D4BE98"

[colors.cursor]
text = "#1F1F1F"
cursor = "#D4D4D4"

[colors.normal]
black = "#3C3836"
red = "#EA6962"
green = "#A9B665"
yellow = "#D8A657"
blue = "#7DAEA3"
magenta = "#D3869B"
cyan = "#89B482"
white = "#D4BE98"

[colors.bright]
black = "#3C3836"
red = "#EA6962"
green = "#A9B665"
yellow = "#D8A657"
blue = "#7DAEA3"
magenta = "#D3869B"
cyan = "#89B482"
white = "#D4BE98"

[colors.selection]
background = "#2D4F67"
text = "#C8C093"

[cursor.style]
shape = "Block"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 10
y = 10

