# color theme
[general]
import = ["./themes/ascua.toml"]

[cursor.style]
shape = "Block"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"

[font.italic]
family = "SauceCodePro Nerd Font Mono"

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[font.offset]
x = 0
y = 1

# keybindings needed to use Alt + hjkl to resize buffers
[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "\u001bh"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\u001bj"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\u001bk"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "\u001bl"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.padding]
x = 10
y = 10

