"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[var]
Username = ""

[palette]
cross = "white"
user = "yellow"
dir = "cyan"
git = "magenta"
closer = "magenta"

[[blocks]]
alignment = "left"
type = "prompt"

    [[blocks.segments]]
    style = "plain"
    foreground = "p:cross"
    template = "󰥓 "
    type = "text"

    [[blocks.segments]]
    foreground = "p:user"
    style = "plain"
    template = "{{ if eq .UserName \"michaelnavarro\" }}mn{{ else }}{{ .UserName }}{{ end }}@{{ .HostName }} "
    type = "session"

    [[blocks.segments]]
    foreground = "p:dir"
    style = "plain"
    template="{{if .Segments.Git.Ref}}{{.Segments.Git.RepoName}}{{.Path | replace .Segments.Git.Dir \"\"}}{{else}}{{.Path}}{{end}} "
    type = "path"

        [blocks.segments.properties]
        style = "full"

    [[blocks.segments]]
    foreground = "p:git"
    style = "plain"
    template = ":: {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }} "
    type = "git"

        [blocks.segments.properties]
        fetch_status = true

[[blocks]]
alignment = "right"
type = "prompt"

    [[blocks.segments]]
    foreground = "red"
    style = "plain"
    template = "| root "
    type = "root"

    [[blocks.segments]]
    type = "react"
    style = "powerline"
    foreground = "blue"
    template = "|  {{ .Full }} "

    [[blocks.segments]]
    type = "angular"
    style = "powerline"
    foreground = "red"
    template = "|  {{ .Full }} "

    [[blocks.segments]]
    type = "npm"
    style = "powerline"
    foreground = "red"
    template = "|  {{ .Full }} "

    [[blocks.segments]]
    type = "node"
    style = "powerline"
    foreground = "green"
    template = "|  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "

    [[blocks.segments]]
    type = "python"
    style = "powerline"
    foreground = "yellow"
    template = "|  {{ .Venv }} "
        [blocks.segments.properties]
        display_mode = "context"
        fetch_virtual_env = true

    [[blocks.segments]]
    type = "go"
    style = "powerline"
    foreground = "blue"
    template = "|  {{ .Full }} "

    [[blocks.segments]]
    type = "dotnet"
    style = "powerline"
    foreground = "blue"
    template = "  {{ .Full }} "

    [[blocks.segments]]
    type = "docker"
    style = "powerline"
    foreground = "blue"
    template = "|  {{ .Context }} "

    [[blocks.segments]]
    type = "lua"
    style = "powerline"
    foreground = "blue"
    template = "|  {{ .Full }} "

    [[blocks.segments]]
    type = "rust"
    style = "powerline"
    foreground = "red"
    template = "|  {{ .Full }} "

    [[blocks.segments]]
    type = "cmake"
    style = "powerline"
    foreground = "yellow"
    template = "|  {{ .Full }} "

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

    [[blocks.segments]]
    foreground = "p:closer"
    foreground_templates = [ "{{ if gt .Code 0 }}red{{ end }}" ]
    style = "powerline"
    template = "➜ "
    type = "status"

        [blocks.segments.properties]
        always_enabled = true

[transient_prompt]
style = "plain"
foreground = "p:closer"
template = "➜ "
type = "text"
