[colors.primary]
background = "#181A1F"
foreground = "#A9B2C3"

[colors.normal]
black = "#5F6672"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#B57EDC"
red = "#E06C75"
white = "#A9B2C3"
yellow = "#E5C07B"

[colors.bright]
black = "#5F6672"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#B57EDC"
red = "#E06C75"
white = "#A9B2C3"
yellow = "#E5C07B"
